services:
  nginx:
    image: nginx:latest
    container_name: vocabulary-nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-conf/ssl:/etc/ssl:ro
    restart: unless-stopped
