# Optional: tune buffers/timeouts if you see 502s on long requests
proxy_http_version 1.1;
proxy_buffering off;

# Pass client details to the apps (important for Keycloak & HTTPS behind proxy)
map $http_x_forwarded_proto $best_proto {
  default $http_x_forwarded_proto;
  ""      $scheme;
}

server {
    listen 80;
    server_name _;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
   listen 443 ssl;
   server_name _;

       # Paths to your SSL certificate and key
   ssl_certificate     /etc/ssl/example.crt;
   ssl_certificate_key /etc/ssl/example.key;


  # ----- Spring Boot API at /rest/ -> host port 9090 -----
  location /rest/ {
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://host.docker.internal:9090/;
  }


  #TODO - remove it
  # ----- Static fake page -----
  location /fake {
    alias /usr/share/nginx/html/;
    index index.html;
  }

  location / {
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://host.docker.internal:18081/;
  }

  # Basic health check
  location = /health {
    return 200 "OK\n";
    add_header Content-Type text/plain;
  }
}