# -------------------------------
# auth.myvocabulary.net
# -------------------------------
server {
    listen 80;
    server_name auth.myvocabulary.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name auth.myvocabulary.net;

    ssl_certificate     /etc/nginx/ssl/auth/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/auth/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:18081/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  443;
        proxy_redirect off;
    }
}

# -------------------------------
# api.myvocabulary.net
# -------------------------------
server {
    listen 80;
    server_name api.myvocabulary.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.myvocabulary.net;

    ssl_certificate     /etc/nginx/ssl/api/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/api/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:9090/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  443;
        proxy_redirect off;
    }
}
