spring:
  datasource:
    url: jdbc:postgresql://vocabulary-db:5432/vocabulary_api
    username: enrico
    password: enrico

application:
  spa:
    url: http://localhost:4200
  keycloak:
    url: http://20.223.169.151:18081
    username: ${KC_BOOTSTRAP_ADMIN_USERNAME}
    password: ${KC_BOOTSTRAP_ADMIN_PASSWORD}

  cors:
    allowed-origins: http://localhost:4200,https://gentle-tree-062b47803.1.azurestaticapps.net



