---
-- #%L
-- Vocabulary API
-- %%
-- Copyright (C) 2024 - 2025 Vocabulary Team
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
INSERT INTO language(code, name)
VALUES ('en', 'English'),
       ('es', 'Spanish'),
       ('fr', 'French'),
       ('de', 'German'),
       ('it', 'Italian'),
       ('ru', 'Russian'),
       ('pt', 'Portuguese'),
       ('zh', 'Chinese'),
       ('ja', 'Japanese'),
       ('ar', 'Arabic'),
       ('hi', 'Hindi'),
       ('ko', 'Korean'),
       ('tr', 'Turkish'),
       ('nl', 'Dutch'),
       ('pl', 'Polish'),
       ('sv', 'Swedish');

-- insert a basic user, can be removed via KC admin console
INSERT INTO vocabulary.user (username, email, keycloakId)
VALUES ('enrico', 'enrico@user.com', 'ab8d6366-3e74-47f0-9c9b-114215b1b99f');

-- Tags
INSERT INTO vocabulary.tag (name) VALUES
('IT'),
('KITCHEN'),
('TRAVEL'),
('SPORT'),
('HEALTH'),
('WORK'),
('SHOPPING'),
('NATURE'),
('EDUCATION'),
('FAMILY'),
('FOOD'),
('TRANSPORT'),
('SOCIAL'),
('FINANCE'),
('HOLIDAY');

INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight)
SELECT t.id, v.keyword, v.weight
FROM vocabulary.tag t
JOIN (VALUES
  ('IT',         'computer',       5),
  ('IT',         'laptop',         5),
  ('IT',         'software',       5),
  ('IT',         'algorithm',      5),
  ('IT',         'programming',    5),
  ('IT',         'code',           5),
  ('IT',         'server',         5),
  ('IT',         'database',       5),
  ('IT',         'internet',       5),
  ('IT',         'network',        4),
  ('IT',         'keyboard',       4),
  ('IT',         'mouse',          4),
  ('IT',         'screen',         3),
  ('IT',         'monitor',        4),
  ('IT',         'bug',            4),
  ('IT',         'developer',      5),
  ('IT',         'application',    4),
  ('IT',         'website',        4),
  ('IT',         'browser',        4),
  ('IT',         'password',       4),
  ('IT',         'cloud',          4),
  ('IT',         'router',         4),
  ('IT',         'processor',      4),
  ('IT',         'wifi',           4),
  ('IT',         'debug',          5),
  ('KITCHEN',    'cook',           5),
  ('KITCHEN',    'recipe',         5),
  ('KITCHEN',    'oven',           5),
  ('KITCHEN',    'ingredient',     5),
  ('KITCHEN',    'bake',           5),
  ('KITCHEN',    'boil',           4),
  ('KITCHEN',    'fry',            4),
  ('KITCHEN',    'knife',          4),
  ('KITCHEN',    'pan',            4),
  ('KITCHEN',    'pot',            4),
  ('KITCHEN',    'spatula',        5),
  ('KITCHEN',    'refrigerator',   5),
  ('KITCHEN',    'microwave',      5),
  ('KITCHEN',    'dough',          5),
  ('KITCHEN',    'simmer',         5),
  ('KITCHEN',    'roast',          5),
  ('KITCHEN',    'chop',           4),
  ('KITCHEN',    'blend',          4),
  ('KITCHEN',    'kitchen',        5),
  ('KITCHEN',    'stove',          5),
  ('KITCHEN',    'grill',          4),
  ('KITCHEN',    'marinate',       5),
  ('KITCHEN',    'seasoning',      5),
  ('KITCHEN',    'whisk',          5),
  ('KITCHEN',    'colander',       5),
  ('TRAVEL',     'hotel',          5),
  ('TRAVEL',     'flight',         5),
  ('TRAVEL',     'airport',        5),
  ('TRAVEL',     'passport',       5),
  ('TRAVEL',     'visa',           5),
  ('TRAVEL',     'luggage',        5),
  ('TRAVEL',     'destination',    4),
  ('TRAVEL',     'tourist',        5),
  ('TRAVEL',     'itinerary',      5),
  ('TRAVEL',     'booking',        4),
  ('TRAVEL',     'sightseeing',    5),
  ('TRAVEL',     'voyage',         5),
  ('TRAVEL',     'backpack',       4),
  ('TRAVEL',     'hostel',         5),
  ('TRAVEL',     'cruise',         5),
  ('TRAVEL',     'landmark',       4),
  ('TRAVEL',     'souvenir',       5),
  ('TRAVEL',     'customs',        5),
  ('TRAVEL',     'boarding',       5),
  ('TRAVEL',     'departure',      5),
  ('TRAVEL',     'arrival',        5),
  ('TRAVEL',     'guidebook',      5),
  ('TRAVEL',     'excursion',      5),
  ('TRAVEL',     'resort',         4),
  ('TRAVEL',     'jet',            4),
  ('SPORT',      'goal',           4),
  ('SPORT',      'match',          5),
  ('SPORT',      'training',       4),
  ('SPORT',      'athlete',        5),
  ('SPORT',      'team',           5),
  ('SPORT',      'competition',    5),
  ('SPORT',      'championship',   5),
  ('SPORT',      'stadium',        5),
  ('SPORT',      'coach',          4),
  ('SPORT',      'player',         5),
  ('SPORT',      'score',          4),
  ('SPORT',      'tournament',     5),
  ('SPORT',      'referee',        5),
  ('SPORT',      'fitness',        4),
  ('SPORT',      'gym',            4),
  ('SPORT',      'race',           4),
  ('SPORT',      'sprint',         5),
  ('SPORT',      'medal',          5),
  ('SPORT',      'trophy',         5),
  ('SPORT',      'league',         5),
  ('SPORT',      'opponent',       4),
  ('SPORT',      'victory',        4),
  ('SPORT',      'goalkeeper',     5),
  ('SPORT',      'dribble',        5),
  ('SPORT',      'penalty',        5),
  ('HEALTH',     'doctor',         5),
  ('HEALTH',     'hospital',       5),
  ('HEALTH',     'medicine',       5),
  ('HEALTH',     'symptom',        5),
  ('HEALTH',     'diagnosis',      5),
  ('HEALTH',     'treatment',      5),
  ('HEALTH',     'patient',        5),
  ('HEALTH',     'nurse',          5),
  ('HEALTH',     'surgery',        5),
  ('HEALTH',     'prescription',   5),
  ('HEALTH',     'pharmacy',       5),
  ('HEALTH',     'vaccine',        5),
  ('HEALTH',     'therapy',        4),
  ('HEALTH',     'disease',        5),
  ('HEALTH',     'infection',      5),
  ('HEALTH',     'fever',          5),
  ('HEALTH',     'allergy',        5),
  ('HEALTH',     'recovery',       4),
  ('HEALTH',     'clinic',         5),
  ('HEALTH',     'specialist',     5),
  ('HEALTH',     'blood',          4),
  ('HEALTH',     'pain',           4),
  ('HEALTH',     'heartbeat',      5),
  ('HEALTH',     'wellness',       4),
  ('HEALTH',     'checkup',        5),
  ('WORK',       'meeting',        5),
  ('WORK',       'deadline',       5),
  ('WORK',       'salary',         5),
  ('WORK',       'office',         5),
  ('WORK',       'colleague',      5),
  ('WORK',       'manager',        5),
  ('WORK',       'project',        4),
  ('WORK',       'contract',       5),
  ('WORK',       'presentation',   5),
  ('WORK',       'promotion',      5),
  ('WORK',       'interview',      5),
  ('WORK',       'career',         4),
  ('WORK',       'client',         4),
  ('WORK',       'schedule',       4),
  ('WORK',       'budget',         4),
  ('WORK',       'conference',     5),
  ('WORK',       'workload',       5),
  ('WORK',       'employee',       5),
  ('WORK',       'employer',       5),
  ('WORK',       'department',     4),
  ('WORK',       'resign',         4),
  ('WORK',       'hire',           4),
  ('WORK',       'overtime',       5),
  ('WORK',       'invoice',        5),
  ('WORK',       'spreadsheet',    5),
  ('SHOPPING',   'price',          4),
  ('SHOPPING',   'discount',       5),
  ('SHOPPING',   'store',          4),
  ('SHOPPING',   'purchase',       4),
  ('SHOPPING',   'receipt',        5),
  ('SHOPPING',   'checkout',       5),
  ('SHOPPING',   'cart',           5),
  ('SHOPPING',   'refund',         5),
  ('SHOPPING',   'sale',           4),
  ('SHOPPING',   'bargain',        5),
  ('SHOPPING',   'brand',          4),
  ('SHOPPING',   'mall',           5),
  ('SHOPPING',   'shipping',       4),
  ('SHOPPING',   'delivery',       4),
  ('SHOPPING',   'order',          4),
  ('SHOPPING',   'coupon',         5),
  ('SHOPPING',   'warranty',       5),
  ('SHOPPING',   'retailer',       5),
  ('SHOPPING',   'wholesale',      5),
  ('SHOPPING',   'catalog',        5),
  ('SHOPPING',   'aisle',          5),
  ('SHOPPING',   'cashier',        5),
  ('SHOPPING',   'exchange',       4),
  ('SHOPPING',   'promotion',      4),
  ('SHOPPING',   'clearance',      5),
  ('NATURE',     'forest',         5),
  ('NATURE',     'river',          5),
  ('NATURE',     'mountain',       5),
  ('NATURE',     'ocean',          5),
  ('NATURE',     'wildlife',       5),
  ('NATURE',     'ecosystem',      5),
  ('NATURE',     'earthquake',     5),
  ('NATURE',     'volcano',        5),
  ('NATURE',     'desert',         5),
  ('NATURE',     'jungle',         5),
  ('NATURE',     'lake',           5),
  ('NATURE',     'valley',         5),
  ('NATURE',     'waterfall',      5),
  ('NATURE',     'animal',         4),
  ('NATURE',     'tree',           4),
  ('NATURE',     'flower',         4),
  ('NATURE',     'bird',           4),
  ('NATURE',     'climate',        4),
  ('NATURE',     'rain',           4),
  ('NATURE',     'snow',           4),
  ('NATURE',     'soil',           4),
  ('NATURE',     'plant',          4),
  ('NATURE',     'glacier',        5),
  ('NATURE',     'tide',           5),
  ('NATURE',     'cave',           5),
  ('EDUCATION',  'school',         5),
  ('EDUCATION',  'lesson',         5),
  ('EDUCATION',  'exam',           5),
  ('EDUCATION',  'student',        5),
  ('EDUCATION',  'teacher',        5),
  ('EDUCATION',  'university',     5),
  ('EDUCATION',  'homework',       5),
  ('EDUCATION',  'course',         5),
  ('EDUCATION',  'degree',         5),
  ('EDUCATION',  'classroom',      5),
  ('EDUCATION',  'textbook',       5),
  ('EDUCATION',  'lecture',        5),
  ('EDUCATION',  'curriculum',     5),
  ('EDUCATION',  'assignment',     5),
  ('EDUCATION',  'tutor',          5),
  ('EDUCATION',  'scholarship',    5),
  ('EDUCATION',  'graduation',     5),
  ('EDUCATION',  'thesis',         5),
  ('EDUCATION',  'professor',      5),
  ('EDUCATION',  'library',        4),
  ('EDUCATION',  'research',       4),
  ('EDUCATION',  'grade',          4),
  ('EDUCATION',  'syllabus',       5),
  ('EDUCATION',  'enrollment',     5),
  ('EDUCATION',  'campus',         5),
  ('FAMILY',     'parent',         5),
  ('FAMILY',     'child',          5),
  ('FAMILY',     'marriage',       5),
  ('FAMILY',     'brother',        5),
  ('FAMILY',     'sister',         5),
  ('FAMILY',     'grandmother',    5),
  ('FAMILY',     'grandfather',    5),
  ('FAMILY',     'uncle',          5),
  ('FAMILY',     'aunt',           5),
  ('FAMILY',     'cousin',         5),
  ('FAMILY',     'wedding',        5),
  ('FAMILY',     'pregnancy',      5),
  ('FAMILY',     'baby',           5),
  ('FAMILY',     'relative',       5),
  ('FAMILY',     'guardian',       5),
  ('FAMILY',     'sibling',        5),
  ('FAMILY',     'spouse',         5),
  ('FAMILY',     'husband',        5),
  ('FAMILY',     'wife',           5),
  ('FAMILY',     'newborn',        5),
  ('FAMILY',     'adoption',       5),
  ('FAMILY',     'divorce',        4),
  ('FAMILY',     'household',      4),
  ('FAMILY',     'nephew',         5),
  ('FAMILY',     'niece',          5),
  ('FOOD',       'restaurant',     5),
  ('FOOD',       'menu',           5),
  ('FOOD',       'dish',           5),
  ('FOOD',       'meal',           5),
  ('FOOD',       'breakfast',      5),
  ('FOOD',       'lunch',          5),
  ('FOOD',       'dinner',         5),
  ('FOOD',       'dessert',        5),
  ('FOOD',       'appetizer',      5),
  ('FOOD',       'waiter',         5),
  ('FOOD',       'flavor',         4),
  ('FOOD',       'spicy',          4),
  ('FOOD',       'sweet',          4),
  ('FOOD',       'salty',          4),
  ('FOOD',       'vegetarian',     5),
  ('FOOD',       'vegan',          5),
  ('FOOD',       'snack',          4),
  ('FOOD',       'buffet',         5),
  ('FOOD',       'chef',           4),
  ('FOOD',       'nutrition',      4),
  ('FOOD',       'portion',        4),
  ('FOOD',       'cuisine',        4),
  ('FOOD',       'takeaway',       5),
  ('FOOD',       'tipping',        4),
  ('FOOD',       'reservation',    4),
  ('SOCIAL',     'friend',         5),
  ('SOCIAL',     'date',           5),
  ('SOCIAL',     'party',          5),
  ('SOCIAL',     'flirt',          5),
  ('SOCIAL',     'invite',         4),
  ('SOCIAL',     'gathering',      5),
  ('SOCIAL',     'chat',           4),
  ('SOCIAL',     'relationship',   5),
  ('SOCIAL',     'crush',          5),
  ('SOCIAL',     'hangout',        5),
  ('SOCIAL',     'breakup',        5),
  ('SOCIAL',     'romance',        5),
  ('SOCIAL',     'hug',            4),
  ('SOCIAL',     'kiss',           5),
  ('SOCIAL',     'gossip',         5),
  ('SOCIAL',     'compliment',     4),
  ('SOCIAL',     'acquaintance',   5),
  ('SOCIAL',     'encounter',      4),
  ('SOCIAL',     'jealousy',       5),
  ('SOCIAL',     'affection',      5),
  ('SOCIAL',     'companionship',  5),
  ('SOCIAL',     'bond',           4),
  ('SOCIAL',     'networking',     4),
  ('SOCIAL',     'celebration',    4),
  ('SOCIAL',     'reunion',        5),
  ('TRANSPORT',  'car',            5),
  ('TRANSPORT',  'train',          5),
  ('TRANSPORT',  'traffic',        5),
  ('TRANSPORT',  'bus',            5),
  ('TRANSPORT',  'taxi',           5),
  ('TRANSPORT',  'bicycle',        5),
  ('TRANSPORT',  'motorcycle',     5),
  ('TRANSPORT',  'highway',        5),
  ('TRANSPORT',  'parking',        5),
  ('TRANSPORT',  'fuel',           5),
  ('TRANSPORT',  'engine',         4),
  ('TRANSPORT',  'brake',          4),
  ('TRANSPORT',  'tire',           4),
  ('TRANSPORT',  'license',        4),
  ('TRANSPORT',  'accident',       4),
  ('TRANSPORT',  'subway',         5),
  ('TRANSPORT',  'tram',           5),
  ('TRANSPORT',  'ferry',          5),
  ('TRANSPORT',  'pedestrian',     4),
  ('TRANSPORT',  'lane',           4),
  ('TRANSPORT',  'roundabout',     5),
  ('TRANSPORT',  'intersection',   5),
  ('TRANSPORT',  'seatbelt',       5),
  ('TRANSPORT',  'overtake',       5),
  ('TRANSPORT',  'congestion',     5),
  ('FINANCE',    'bank',           5),
  ('FINANCE',    'loan',           5),
  ('FINANCE',    'mortgage',       5),
  ('FINANCE',    'investment',     5),
  ('FINANCE',    'interest',       5),
  ('FINANCE',    'dividend',       5),
  ('FINANCE',    'stock',          5),
  ('FINANCE',    'tax',            5),
  ('FINANCE',    'inflation',      5),
  ('FINANCE',    'savings',        5),
  ('FINANCE',    'debt',           5),
  ('FINANCE',    'budget',         4),
  ('FINANCE',    'currency',       5),
  ('FINANCE',    'exchange',       4),
  ('FINANCE',    'profit',         5),
  ('FINANCE',    'revenue',        5),
  ('FINANCE',    'expense',        5),
  ('FINANCE',    'insurance',      5),
  ('FINANCE',    'pension',        5),
  ('FINANCE',    'portfolio',      5),
  ('FINANCE',    'withdrawal',     5),
  ('FINANCE',    'deposit',        5),
  ('FINANCE',    'cryptocurrency', 5),
  ('FINANCE',    'accountant',     5),
  ('FINANCE',    'audit',          5),
  ('HOLIDAY',    'beach',          5),
  ('HOLIDAY',    'sunscreen',      5),
  ('HOLIDAY',    'swimsuit',       5),
  ('HOLIDAY',    'sunbathe',       5),
  ('HOLIDAY',    'resort',         5),
  ('HOLIDAY',    'vacation',       5),
  ('HOLIDAY',    'suitcase',       5),
  ('HOLIDAY',    'sunburn',        5),
  ('HOLIDAY',    'snorkeling',     5),
  ('HOLIDAY',    'tan',            4),
  ('HOLIDAY',    'relaxation',     4),
  ('HOLIDAY',    'umbrella',       4),
  ('HOLIDAY',    'hammock',        5),
  ('HOLIDAY',    'sandcastle',     5),
  ('HOLIDAY',    'pool',           4),
  ('HOLIDAY',    'cocktail',       4),
  ('HOLIDAY',    'charter',        5),
  ('HOLIDAY',    'all-inclusive',  5),
  ('HOLIDAY',    'sightseeing',    4),
  ('HOLIDAY',    'sunglasses',     4),
  ('HOLIDAY',    'postcard',       5),
  ('HOLIDAY',    'shore',          4),
  ('HOLIDAY',    'wave',           4),
  ('HOLIDAY',    'surf',           5),
  ('HOLIDAY',    'getaway',        5)
) AS v(tag_name, keyword, weight) ON t.name = v.tag_name;