---
-- #%L
-- Vocabulary API
-- %%
-- Copyright (C) 2024 - 2025 Vocabulary Team
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
INSERT INTO language(code, name)
VALUES ('en', 'English'),
       ('es', 'Spanish'),
       ('fr', 'French'),
       ('de', 'German'),
       ('it', 'Italian'),
       ('ru', 'Russian'),
       ('pt', 'Portuguese'),
       ('zh', 'Chinese'),
       ('ja', 'Japanese'),
       ('ar', 'Arabic'),
       ('hi', 'Hindi'),
       ('ko', 'Korean'),
       ('tr', 'Turkish'),
       ('nl', 'Dutch'),
       ('pl', 'Polish'),
       ('sv', 'Swedish');

-- insert a basic user, can be removed via KC admin console
INSERT INTO vocabulary.user (username, email, keycloakId)
VALUES ('enrico', 'enrico@user.com', 'ab8d6366-3e74-47f0-9c9b-114215b1b99f');

-- Tags
INSERT INTO vocabulary.tag (name) VALUES
('IT'),
('KITCHEN'),
('TRAVEL'),
('SPORT'),
('HEALTH'),
('WORK'),
('SHOPPING'),
('NATURE'),
('EDUCATION'),
('FAMILY'),
('FOOD'),
('TRANSPORT'),
('SOCIAL'),
('FINANCE'),
('HOLIDAY');

-- IT
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'computer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'laptop', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'software', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'algorithm', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'programming', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'code', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'server', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'database', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'internet', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'network', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'keyboard', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'mouse', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'screen', 3),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'monitor', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'bug', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'developer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'application', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'website', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'browser', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'password', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'cloud', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'router', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'processor', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'wifi', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'IT'), 'debug', 5);

-- KITCHEN
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'cook', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'recipe', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'oven', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'ingredient', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'bake', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'boil', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'fry', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'knife', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'pan', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'pot', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'spatula', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'refrigerator', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'microwave', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'dough', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'simmer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'roast', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'chop', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'blend', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'kitchen', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'stove', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'grill', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'marinate', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'seasoning', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'whisk', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'KITCHEN'), 'colander', 5);

-- TRAVEL
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'hotel', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'flight', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'airport', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'passport', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'visa', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'luggage', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'destination', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'tourist', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'itinerary', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'booking', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'sightseeing', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'voyage', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'backpack', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'hostel', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'cruise', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'landmark', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'souvenir', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'customs', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'boarding', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'departure', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'arrival', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'guidebook', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'excursion', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'resort', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRAVEL'), 'jet', 4);

-- SPORT
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'goal', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'match', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'training', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'athlete', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'team', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'competition', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'championship', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'stadium', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'coach', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'player', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'score', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'tournament', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'referee', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'fitness', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'gym', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'race', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'sprint', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'medal', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'trophy', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'league', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'opponent', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'victory', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'goalkeeper', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'dribble', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SPORT'), 'penalty', 5);

-- HEALTH
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'doctor', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'hospital', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'medicine', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'symptom', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'diagnosis', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'treatment', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'patient', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'nurse', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'surgery', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'prescription', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'pharmacy', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'vaccine', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'therapy', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'disease', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'infection', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'fever', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'allergy', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'recovery', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'clinic', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'specialist', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'blood', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'pain', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'heartbeat', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'wellness', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HEALTH'), 'checkup', 5);

-- WORK
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'meeting', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'deadline', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'salary', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'office', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'colleague', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'manager', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'project', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'contract', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'presentation', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'promotion', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'interview', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'career', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'client', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'schedule', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'budget', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'conference', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'workload', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'employee', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'employer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'department', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'resign', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'hire', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'overtime', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'invoice', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'WORK'), 'spreadsheet', 5);

-- SHOPPING
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'price', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'discount', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'store', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'purchase', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'receipt', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'checkout', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'cart', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'refund', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'sale', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'bargain', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'brand', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'mall', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'shipping', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'delivery', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'order', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'coupon', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'warranty', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'retailer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'wholesale', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'catalog', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'aisle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'cashier', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'exchange', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'promotion', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SHOPPING'), 'clearance', 5);

-- NATURE
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'forest', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'river', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'mountain', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'ocean', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'wildlife', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'ecosystem', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'earthquake', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'volcano', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'desert', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'jungle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'lake', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'valley', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'waterfall', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'animal', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'tree', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'flower', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'bird', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'climate', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'rain', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'snow', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'soil', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'plant', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'glacier', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'tide', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'NATURE'), 'cave', 5);

-- EDUCATION
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'school', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'lesson', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'exam', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'student', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'teacher', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'university', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'homework', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'course', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'degree', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'classroom', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'textbook', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'lecture', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'curriculum', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'assignment', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'tutor', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'scholarship', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'graduation', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'thesis', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'professor', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'library', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'research', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'grade', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'syllabus', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'enrollment', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'EDUCATION'), 'campus', 5);

-- FAMILY
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'parent', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'child', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'marriage', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'brother', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'sister', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'grandmother', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'grandfather', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'uncle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'aunt', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'cousin', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'wedding', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'pregnancy', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'baby', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'relative', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'guardian', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'sibling', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'spouse', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'husband', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'wife', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'newborn', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'adoption', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'divorce', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'household', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'nephew', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FAMILY'), 'niece', 5);

-- FOOD
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'restaurant', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'menu', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'dish', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'meal', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'breakfast', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'lunch', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'dinner', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'dessert', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'appetizer', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'waiter', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'flavor', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'spicy', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'sweet', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'salty', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'vegetarian', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'vegan', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'snack', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'buffet', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'chef', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'nutrition', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'portion', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'cuisine', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'takeaway', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'tipping', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FOOD'), 'reservation', 4);

-- SOCIAL
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'friend', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'date', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'party', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'flirt', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'invite', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'gathering', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'chat', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'relationship', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'crush', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'hangout', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'breakup', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'romance', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'hug', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'kiss', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'gossip', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'compliment', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'acquaintance', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'encounter', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'jealousy', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'affection', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'companionship', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'bond', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'networking', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'celebration', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'SOCIAL'), 'reunion', 5);

-- TRANSPORT
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'car', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'train', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'traffic', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'bus', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'taxi', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'bicycle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'motorcycle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'highway', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'parking', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'fuel', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'engine', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'brake', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'tire', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'license', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'accident', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'subway', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'tram', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'ferry', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'pedestrian', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'lane', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'roundabout', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'intersection', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'seatbelt', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'overtake', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'TRANSPORT'), 'congestion', 5);

-- FINANCE
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'bank', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'loan', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'mortgage', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'investment', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'interest', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'dividend', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'stock', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'tax', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'inflation', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'savings', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'debt', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'budget', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'currency', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'exchange', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'profit', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'revenue', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'expense', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'insurance', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'pension', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'portfolio', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'withdrawal', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'deposit', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'cryptocurrency', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'accountant', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'FINANCE'), 'audit', 5);

-- HOLIDAY
INSERT INTO vocabulary.tag_keyword (tag_id, keyword, weight) VALUES
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'beach', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sunscreen', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'swimsuit', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sunbathe', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'resort', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'vacation', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'suitcase', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sunburn', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'snorkeling', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'tan', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'relaxation', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'umbrella', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'hammock', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sandcastle', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'pool', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'cocktail', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'charter', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'all-inclusive', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sightseeing', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'sunglasses', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'postcard', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'shore', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'wave', 4),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'surf', 5),
((SELECT id FROM vocabulary.tag WHERE name = 'HOLIDAY'), 'getaway', 5);