-- #%L
-- Vocabulary API
-- %%
-- Copyright (C) 2024 - 2026 Vocabulary Team
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%

CREATE TYPE vocabulary.article AS ENUM ('der', 'die', 'das');

CREATE TABLE vocabulary.public_noun_de
(
    id                 SERIAL PRIMARY KEY,
    word_de            VARCHAR(256)       NOT NULL,
    article            vocabulary.article NOT NULL,
    plural_de          VARCHAR(256)       NULL,
    plural_distractors TEXT[]             NULL,
    created_at         TIMESTAMPTZ        NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ        NOT NULL DEFAULT now(),
    external_id        UUID               NOT NULL UNIQUE DEFAULT gen_random_uuid()
);

CREATE TABLE vocabulary.public_noun_de_translation
(
    id          SERIAL PRIMARY KEY,
    noun_id     INT          NOT NULL REFERENCES vocabulary.public_noun_de (id),
    lang        VARCHAR(5)   NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 1,
    translation VARCHAR(256) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (noun_id, lang, sort_order)
);

CREATE TABLE vocabulary.public_noun_de_example
(
    id                   SERIAL PRIMARY KEY,
    translation_id       INT         NOT NULL REFERENCES vocabulary.public_noun_de_translation (id),
    sentence_de          TEXT        NOT NULL,
    sentence_translation TEXT        NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO vocabulary.public_noun_de (word_de, article, plural_de, plural_distractors) VALUES

-- der (masculine)
('Mann',             'der', 'Männer',           ARRAY['Manner', 'Manne', 'Mannen']),
('Vater',            'der', 'Väter',            ARRAY['Vatern', 'Vätern', 'Vaters']),
('Bruder',           'der', 'Brüder',           ARRAY['Bruder', 'Brüdern', 'Brudern']),
('Sohn',             'der', 'Söhne',            ARRAY['Sohne', 'Söhnen', 'Sohnen']),
('Freund',           'der', 'Freunde',          ARRAY['Freunden', 'Freunder', 'Freunds']),
('Tag',              'der', 'Tage',             ARRAY['Tagen', 'Tags', 'Tager']),
('Morgen',           'der', 'Morgen',           ARRAY['Morgens', 'Morgene', 'Morgenen']),
('Abend',            'der', 'Abende',           ARRAY['Abenden', 'Abends', 'Abender']),
('Monat',            'der', 'Monate',           ARRAY['Monaten', 'Monats', 'Monater']),
('Sommer',           'der', 'Sommer',           ARRAY['Sommers', 'Sommere', 'Sommern']),
('Winter',           'der', 'Winter',           ARRAY['Winters', 'Wintere', 'Wintern']),
('Herbst',           'der', 'Herbste',          ARRAY['Herbsten', 'Herbsts', 'Herbster']),
('Frühling',         'der', 'Frühlinge',        ARRAY['Frühlingen', 'Frühlings', 'Frühlinger']),
('Beruf',            'der', 'Berufe',           ARRAY['Berufen', 'Berufs', 'Berufer']),
('Tisch',            'der', 'Tische',           ARRAY['Tischen', 'Tischs', 'Tischer']),
('Stuhl',            'der', 'Stühle',           ARRAY['Stuhle', 'Stühlen', 'Stuhlen']),
('Weg',              'der', 'Wege',             ARRAY['Wegen', 'Wegs', 'Weger']),
('Baum',             'der', 'Bäume',            ARRAY['Baume', 'Bäumen', 'Baumen']),
('Berg',             'der', 'Berge',            ARRAY['Bergen', 'Bergs', 'Berger']),
('Hund',             'der', 'Hunde',            ARRAY['Hunden', 'Hunds', 'Hunder']),
('Vogel',            'der', 'Vögel',            ARRAY['Vogel', 'Vögeln', 'Vogeln']),
('Fisch',            'der', 'Fische',           ARRAY['Fischen', 'Fischs', 'Fisches']),
('Apfel',            'der', 'Äpfel',            ARRAY['Apfel', 'Äpfeln', 'Apfeln']),
('Käse',             'der', 'Käse',             ARRAY['Käsen', 'Kaser', 'Käser']),
('Kaffee',           'der', 'Kaffees',          ARRAY['Kaffeen', 'Kaffeer', 'Kaffeeen']),
('Tee',              'der', 'Tees',             ARRAY['Teen', 'Teer', 'Teese']),
('Arzt',             'der', 'Ärzte',            ARRAY['Arzte', 'Ärzten', 'Arzten']),
('Lehrer',           'der', 'Lehrer',           ARRAY['Lehrers', 'Lehrere', 'Lehrern']),
('Student',          'der', 'Studenten',        ARRAY['Studente', 'Students', 'Studentens']),
('Computer',         'der', 'Computer',         ARRAY['Computers', 'Computere', 'Computern']),
('Film',             'der', 'Filme',            ARRAY['Filmen', 'Films', 'Filmer']),
('Bus',              'der', 'Busse',            ARRAY['Bussen', 'Buse', 'Buses']),
('Zug',              'der', 'Züge',             ARRAY['Zuge', 'Zügen', 'Zugen']),
('Garten',           'der', 'Gärten',           ARRAY['Gartens', 'Gartene', 'Gärterns']),
('Park',             'der', 'Parks',            ARRAY['Parke', 'Parken', 'Pärke']),
('Himmel',           'der', 'Himmel',           ARRAY['Himmels', 'Himmele', 'Himmeln']),
('Name',             'der', 'Namen',            ARRAY['Namens', 'Namer', 'Namene']),
('Fluss',            'der', 'Flüsse',           ARRAY['Flusse', 'Flüssen', 'Flussen']),
('Brief',            'der', 'Briefe',           ARRAY['Briefen', 'Briefs', 'Briefer']),
('Markt',            'der', 'Märkte',           ARRAY['Markte', 'Märkten', 'Markten']),
('Schlüssel',        'der', 'Schlüssel',        ARRAY['Schlüssels', 'Schlüssele', 'Schlüsseln']),
('Regen',            'der', NULL,               ARRAY['Regens', 'Regene', 'Regener']),
('Schnee',           'der', NULL,               ARRAY['Schnees', 'Schneen', 'Schneie']),
('Wind',             'der', 'Winde',            ARRAY['Winden', 'Winds', 'Winder']),
('Mond',             'der', 'Monde',            ARRAY['Monden', 'Monds', 'Monder']),
('Stern',            'der', 'Sterne',           ARRAY['Sternen', 'Sterns', 'Sterner']),
('König',            'der', 'Könige',           ARRAY['Königen', 'Königs', 'Königer']),
('Schuh',            'der', 'Schuhe',           ARRAY['Schuhen', 'Schuhs', 'Schuer']),
('Fehler',           'der', 'Fehler',           ARRAY['Fehlers', 'Fehlere', 'Fehlern']),
('Preis',            'der', 'Preise',           ARRAY['Preisen', 'Preiser', 'Preiss']),
('Körper',           'der', 'Körper',           ARRAY['Körpers', 'Körpere', 'Körpern']),
('Kopf',             'der', 'Köpfe',            ARRAY['Kopfe', 'Köpfen', 'Kopfen']),
('Arm',              'der', 'Arme',             ARRAY['Armen', 'Arms', 'Armer']),
('Finger',           'der', 'Finger',           ARRAY['Fingers', 'Fingere', 'Fingern']),
('Fuß',              'der', 'Füße',             ARRAY['Fuse', 'Füßen', 'Fußen']),
('Rücken',           'der', 'Rücken',           ARRAY['Rückens', 'Rückene', 'Rückern']),
('Bauch',            'der', 'Bäuche',           ARRAY['Bauche', 'Bäuchen', 'Bauchen']),
('Mund',             'der', 'Münder',           ARRAY['Munde', 'Münden', 'Munden']),
('Hals',             'der', 'Hälse',            ARRAY['Halse', 'Hälsen', 'Halsen']),
('Zahn',             'der', 'Zähne',            ARRAY['Zahne', 'Zähnen', 'Zahnen']),
('Bart',             'der', 'Bärte',            ARRAY['Barte', 'Bärten', 'Barten']),
('Haare',            'der', NULL,               ARRAY['Haaren', 'Haares', 'Haars']),
('Laden',            'der', 'Läden',            ARRAY['Ladens', 'Ladene', 'Ladenen']),
('Supermarkt',       'der', 'Supermärkte',      ARRAY['Supermarkte', 'Supermärkten', 'Supermarkten']),
('Bäcker',           'der', 'Bäcker',           ARRAY['Bäckers', 'Bäckere', 'Bäckern']),
('Metzger',          'der', 'Metzger',          ARRAY['Metzgers', 'Metzgere', 'Metzgern']),
('Kellner',          'der', 'Kellner',          ARRAY['Kellners', 'Kellnere', 'Kellnern']),
('Fahrer',           'der', 'Fahrer',           ARRAY['Fahrers', 'Fahrere', 'Fahrern']),
('Ingenieur',        'der', 'Ingenieure',       ARRAY['Ingenieuren', 'Ingenieurs', 'Ingenieurer']),
('Anwalt',           'der', 'Anwälte',          ARRAY['Anwalte', 'Anwälten', 'Anwalten']),
('Politiker',        'der', 'Politiker',        ARRAY['Politikers', 'Politikere', 'Politikern']),
('Soldat',           'der', 'Soldaten',         ARRAY['Soldate', 'Soldatens', 'Soldats']),
('Pilot',            'der', 'Piloten',          ARRAY['Pilote', 'Pilotens', 'Pilots']),
('Koch',             'der', 'Köche',            ARRAY['Koche', 'Köchen', 'Kochen']),
('Bauer',            'der', 'Bauern',           ARRAY['Bauers', 'Bauren', 'Baurer']),
('Künstler',         'der', 'Künstler',         ARRAY['Künstlers', 'Künstlere', 'Künstlern']),
('Musiker',          'der', 'Musiker',          ARRAY['Musikers', 'Musikere', 'Musikern']),
('Sportler',         'der', 'Sportler',         ARRAY['Sportlers', 'Sportlere', 'Sportlern']),
('Schüler',          'der', 'Schüler',          ARRAY['Schülers', 'Schülere', 'Schülern']),
('Nachbar',          'der', 'Nachbarn',         ARRAY['Nachbare', 'Nachbars', 'Nachbaren']),
('Gast',             'der', 'Gäste',            ARRAY['Gaste', 'Gästen', 'Gasten']),
('Freier',           'der', NULL,               ARRAY['Freiers', 'Freiere', 'Freiern']),
('Boden',            'der', 'Böden',            ARRAY['Bodens', 'Bodene', 'Bodener']),
('Raum',             'der', 'Räume',            ARRAY['Raume', 'Räumen', 'Raumen']),
('Platz',            'der', 'Plätze',           ARRAY['Platze', 'Plätzen', 'Platzen']),
('Eingang',          'der', 'Eingänge',         ARRAY['Eingange', 'Eingängen', 'Eingangen']),
('Ausgang',          'der', 'Ausgänge',         ARRAY['Ausgange', 'Ausgängen', 'Ausgangen']),
('Aufzug',           'der', 'Aufzüge',          ARRAY['Aufzuge', 'Aufzügen', 'Aufzugen']),
('Keller',           'der', 'Keller',           ARRAY['Kellers', 'Kellere', 'Kellern']),
('Dachboden',        'der', 'Dachböden',        ARRAY['Dachbodens', 'Dachbodene', 'Dachbödener']),
('Schrank',          'der', 'Schränke',         ARRAY['Schranke', 'Schränken', 'Schranken']),
('Spiegel',          'der', 'Spiegel',          ARRAY['Spiegels', 'Spiegele', 'Spiegeln']),
('Teppich',          'der', 'Teppiche',         ARRAY['Teppichen', 'Teppichs', 'Teppiches']),
('Vorhang',          'der', 'Vorhänge',         ARRAY['Vorhange', 'Vorhängen', 'Vorhangen']),
('Herd',             'der', 'Herde',            ARRAY['Herden', 'Herds', 'Herder']),
('Kühlschrank',      'der', 'Kühlschränke',     ARRAY['Kühlschranke', 'Kühlschränken', 'Kühlschranken']),
('Fernseher',        'der', 'Fernseher',        ARRAY['Fernsehers', 'Fernsehern', 'Fernseherer']),
('Drucker',          'der', 'Drucker',          ARRAY['Druckers', 'Druckere', 'Druckern']),
('Stecker',          'der', 'Stecker',          ARRAY['Steckers', 'Steckere', 'Steckern']),
('Schalter',         'der', 'Schalter',         ARRAY['Schalters', 'Schaltere', 'Schaltern']),
('Topf',             'der', 'Töpfe',            ARRAY['Topfe', 'Töpfen', 'Topfen']),
('Löffel',           'der', 'Löffel',           ARRAY['Löffels', 'Löffele', 'Löffeln']),
('Teller',           'der', 'Teller',           ARRAY['Tellers', 'Tellere', 'Tellern']),
('Becher',           'der', 'Becher',           ARRAY['Bechers', 'Bechere', 'Bechern']),
('Stift',            'der', 'Stifte',           ARRAY['Stiften', 'Stifts', 'Stifter']),
('Bleistift',        'der', 'Bleistifte',       ARRAY['Bleistiften', 'Bleistifts', 'Bleistifter']),
('Kalender',         'der', 'Kalender',         ARRAY['Kalenders', 'Kalendere', 'Kalendern']),
('Ausweis',          'der', 'Ausweise',         ARRAY['Ausweisen', 'Ausweiser', 'Ausweiss']),
('Reisepass',        'der', 'Reisepässe',       ARRAY['Reisepasse', 'Reisepässen', 'Reisepassen']),
('Führerschein',     'der', 'Führerscheine',    ARRAY['Führerscheinen', 'Führerscheins', 'Führerscheiner']),
('Vertrag',          'der', 'Verträge',         ARRAY['Vertrage', 'Verträgen', 'Vertragen']),
('Antrag',           'der', 'Anträge',          ARRAY['Antrage', 'Anträgen', 'Antragen']),
('Bericht',          'der', 'Berichte',         ARRAY['Berichten', 'Berichts', 'Berichter']),
('Artikel',          'der', 'Artikel',          ARRAY['Artikels', 'Artikele', 'Artikeln']),
('Roman',            'der', 'Romane',           ARRAY['Romanen', 'Romans', 'Romaner']),
('Autor',            'der', 'Autoren',          ARRAY['Autore', 'Autors', 'Autorens']),
('Verlag',           'der', 'Verlage',          ARRAY['Verlagen', 'Verlags', 'Verlager']),
('Lärm',             'der', NULL,               ARRAY['Lärms', 'Lärme', 'Lärmen']),
('Geruch',           'der', 'Gerüche',          ARRAY['Geruche', 'Gerüchen', 'Geruchen']),
('Geschmack',        'der', 'Geschmäcke',       ARRAY['Geschmacke', 'Geschmäcken', 'Geschmacken']),
('Traum',            'der', 'Träume',           ARRAY['Traume', 'Träumen', 'Traumen']),
('Gedanke',          'der', 'Gedanken',         ARRAY['Gedankes', 'Gedankener', 'Gedankens']),
('Witz',             'der', 'Witze',            ARRAY['Witzen', 'Witzs', 'Witzes']),
('Krach',            'der', NULL,               ARRAY['Krachs', 'Krache', 'Krachen']),
('Schaden',          'der', 'Schäden',          ARRAY['Schadens', 'Schadene', 'Schädener']),
('Unfall',           'der', 'Unfälle',          ARRAY['Unfalle', 'Unfällen', 'Unfallen']),
('Brand',            'der', 'Brände',           ARRAY['Brande', 'Bränden', 'Branden']),
('Sturm',            'der', 'Stürme',           ARRAY['Sturme', 'Stürmen', 'Sturmen']),
('Nebel',            'der', 'Nebel',            ARRAY['Nebels', 'Nebele', 'Nebeln']),
('Frost',            'der', 'Fröste',           ARRAY['Froste', 'Frösten', 'Frosten']),
('Schatten',         'der', 'Schatten',         ARRAY['Schattens', 'Schattene', 'Schattern']),
('Sonnenuntergang',  'der', 'Sonnenuntergänge', ARRAY['Sonnenuntergange', 'Sonnenuntergängen', 'Sonnenuntergangen']),
('Sonnenaufgang',    'der', 'Sonnenaufgänge',   ARRAY['Sonnenaufgange', 'Sonnenaufgängen', 'Sonnenaufgangen']),
('Wald',             'der', 'Wälder',           ARRAY['Walde', 'Wäldern', 'Walden']),
('See',              'der', 'Seen',             ARRAY['Sees', 'Sehe', 'Seer']),
('Strand',           'der', 'Strände',          ARRAY['Strande', 'Stränden', 'Stranden']),
('Sand',             'der', NULL,               ARRAY['Sands', 'Sande', 'Sanden']),
('Stein',            'der', 'Steine',           ARRAY['Steinen', 'Steins', 'Steiner']),
('Fels',             'der', 'Felsen',           ARRAY['Felse', 'Felser', 'Felss']),
('Hügel',            'der', 'Hügel',            ARRAY['Hügels', 'Hügele', 'Hügeln']),
('Vulkan',           'der', 'Vulkane',          ARRAY['Vulkanen', 'Vulkans', 'Vulkaner']),
('Flug',             'der', 'Flüge',            ARRAY['Fluge', 'Flügen', 'Flugen']),
('Hafen',            'der', 'Häfen',            ARRAY['Hafens', 'Hafene', 'Häfener']),
('Bahnhof',          'der', 'Bahnhöfe',         ARRAY['Bahnhofe', 'Bahnhöfen', 'Bahnhofen']),
('Flughafen',        'der', 'Flughäfen',        ARRAY['Flughafens', 'Flughafene', 'Flughäfener']),
('Stau',             'der', 'Staus',            ARRAY['Stauen', 'Staue', 'Stauer']),
('Kilometer',        'der', 'Kilometer',        ARRAY['Kilometers', 'Kilometere', 'Kilometern']),
('Meter',            'der', 'Meter',            ARRAY['Meters', 'Metere', 'Metern']),
('Liter',            'der', 'Liter',            ARRAY['Liters', 'Litere', 'Litern']),
('Grad',             'der', 'Grade',            ARRAY['Graden', 'Grads', 'Grader']),
('Euro',             'der', 'Euro',             ARRAY['Euros', 'Euren', 'Euroe']),
('Cent',             'der', 'Cent',             ARRAY['Cents', 'Centen', 'Cente']),
('Gewinn',           'der', 'Gewinne',          ARRAY['Gewinnen', 'Gewinns', 'Gewinnens']),
('Verlust',          'der', 'Verluste',         ARRAY['Verlusten', 'Verlusts', 'Verluster']),
('Kredit',           'der', 'Kredite',          ARRAY['Krediten', 'Kredits', 'Krediter']),
('Rabatt',           'der', 'Rabatte',          ARRAY['Rabatten', 'Rabatts', 'Rabatter']),
('Scheck',           'der', 'Schecks',          ARRAY['Schecken', 'Schecker', 'Scheckens']),
('Betrag',           'der', 'Beträge',          ARRAY['Betrage', 'Beträgen', 'Betragen']),
('Unterschied',      'der', 'Unterschiede',     ARRAY['Unterschieden', 'Unterschieds', 'Unterschieder']),
('Vorteil',          'der', 'Vorteile',         ARRAY['Vorteilen', 'Vorteils', 'Vorteiler']),
('Nachteil',         'der', 'Nachteile',        ARRAY['Nachteilen', 'Nachteils', 'Nachteiler']),
('Erfolg',           'der', 'Erfolge',          ARRAY['Erfolgen', 'Erfolgs', 'Erfolger']),
('Misserfolg',       'der', 'Misserfolge',      ARRAY['Misserfolgen', 'Misserfolgs', 'Misserfolgern']),
('Anfang',           'der', 'Anfänge',          ARRAY['Anfange', 'Anfängen', 'Anfangen']),
('Schluss',          'der', 'Schlüsse',         ARRAY['Schlusse', 'Schlüssen', 'Schlussen']),
('Grund',            'der', 'Gründe',           ARRAY['Grunde', 'Gründen', 'Grunden']),
('Zweck',            'der', 'Zwecke',           ARRAY['Zwecken', 'Zwecks', 'Zwecker']),
('Schritt',          'der', 'Schritte',         ARRAY['Schritten', 'Schritts', 'Schritter']),
('Fortschritt',      'der', 'Fortschritte',     ARRAY['Fortschritten', 'Fortschritts', 'Fortschritter']),
('Versuch',          'der', 'Versuche',         ARRAY['Versuchen', 'Versuchs', 'Versucher']),
('Beweis',           'der', 'Beweise',          ARRAY['Beweisen', 'Beweiser', 'Beweiss']),
('Begriff',          'der', 'Begriffe',         ARRAY['Begriffen', 'Begriffs', 'Begriffer']),
('Satz',             'der', 'Sätze',            ARRAY['Satze', 'Sätzen', 'Satzen']),

-- die (feminine)
('Frau',             'die', 'Frauen',           ARRAY['Fraue', 'Fraus', 'Fraun']),
('Mutter',           'die', 'Mütter',           ARRAY['Muttern', 'Mutters', 'Mütters']),
('Schwester',        'die', 'Schwestern',       ARRAY['Schwestere', 'Schwesters', 'Schwesterns']),
('Tochter',          'die', 'Töchter',          ARRAY['Tochtern', 'Tochtere', 'Töchtern']),
('Zeit',             'die', 'Zeiten',           ARRAY['Zeite', 'Zeits', 'Zeitens']),
('Nacht',            'die', 'Nächte',           ARRAY['Nachte', 'Nächten', 'Nachten']),
('Woche',            'die', 'Wochen',           ARRAY['Woches', 'Wochens', 'Wochener']),
('Schule',           'die', 'Schulen',          ARRAY['Schules', 'Schulens', 'Schuler']),
('Arbeit',           'die', 'Arbeiten',         ARRAY['Arbeite', 'Arbeitens', 'Arbeits']),
('Stadt',            'die', 'Städte',           ARRAY['Stadte', 'Städten', 'Stadten']),
('Straße',           'die', 'Straßen',          ARRAY['Straßes', 'Straßener', 'Straßere']),
('Familie',          'die', 'Familien',         ARRAY['Familieen', 'Families', 'Familiener']),
('Küche',            'die', 'Küchen',           ARRAY['Küches', 'Küchens', 'Küchener']),
('Sprache',          'die', 'Sprachen',         ARRAY['Spraches', 'Sprachens', 'Sprachener']),
('Musik',            'die', NULL,               ARRAY['Musiken', 'Musiks', 'Musikene']),
('Katze',            'die', 'Katzen',           ARRAY['Katzes', 'Katzens', 'Katzener']),
('Blume',            'die', 'Blumen',           ARRAY['Blumes', 'Blumens', 'Blumener']),
('Sonne',            'die', 'Sonnen',           ARRAY['Sonnes', 'Sonnens', 'Sonnener']),
('Brücke',           'die', 'Brücken',          ARRAY['Brucken', 'Brückes', 'Brückener']),
('Uhr',              'die', 'Uhren',            ARRAY['Uhre', 'Uhres', 'Uhrs']),
('Zeitung',          'die', 'Zeitungen',        ARRAY['Zeitunge', 'Zeitungs', 'Zeitunger']),
('Tasche',           'die', 'Taschen',          ARRAY['Tasches', 'Taschens', 'Taschener']),
('Farbe',            'die', 'Farben',           ARRAY['Farbes', 'Farbens', 'Farbener']),
('Antwort',          'die', 'Antworten',        ARRAY['Antworte', 'Antworts', 'Antworter']),
('Frage',            'die', 'Fragen',           ARRAY['Frages', 'Fragens', 'Fragener']),
('Geschichte',       'die', 'Geschichten',      ARRAY['Geschichtes', 'Geschichter', 'Geschichtens']),
('Kirche',           'die', 'Kirchen',          ARRAY['Kirches', 'Kirchens', 'Kirchener']),
('Wohnung',          'die', 'Wohnungen',        ARRAY['Wohnungs', 'Wohnunge', 'Wohnungener']),
('Milch',            'die', NULL,               ARRAY['Milchen', 'Milchs', 'Milche']),
('Suppe',            'die', 'Suppen',           ARRAY['Suppes', 'Suppens', 'Suppener']),
('Hand',             'die', 'Hände',            ARRAY['Hande', 'Händen', 'Handen']),
('Nase',             'die', 'Nasen',            ARRAY['Nases', 'Nasens', 'Nasener']),
('Nummer',           'die', 'Nummern',          ARRAY['Nummere', 'Nummers', 'Nummernes']),
('Adresse',          'die', 'Adressen',         ARRAY['Adresses', 'Adressener', 'Adressens']),
('Tür',              'die', 'Türen',            ARRAY['Türe', 'Türs', 'Türens']),
('Wand',             'die', 'Wände',            ARRAY['Wande', 'Wänden', 'Wanden']),
('Treppe',           'die', 'Treppen',          ARRAY['Treppes', 'Treppens', 'Treppener']),
('Insel',            'die', 'Inseln',           ARRAY['Insele', 'Insels', 'Inselens']),
('Luft',             'die', 'Lüfte',            ARRAY['Lufte', 'Lüften', 'Luften']),
('Natur',            'die', NULL,               ARRAY['Naturen', 'Naturs', 'Nature']),
('Reise',            'die', 'Reisen',           ARRAY['Reises', 'Reisens', 'Reisener']),
('Stunde',           'die', 'Stunden',          ARRAY['Stundes', 'Stundens', 'Stundener']),
('Minute',           'die', 'Minuten',          ARRAY['Minutes', 'Minutens', 'Minutener']),
('Küste',            'die', 'Küsten',           ARRAY['Kuste', 'Küstes', 'Küstener']),
('Welt',             'die', 'Welten',           ARRAY['Weltens', 'Welts', 'Welter']),
('Freundin',         'die', 'Freundinnen',      ARRAY['Freundine', 'Freundins', 'Freundinen']),
('Lehrerin',         'die', 'Lehrerinnen',      ARRAY['Lehrerins', 'Lehrerine', 'Lehrerinen']),
('Sache',            'die', 'Sachen',           ARRAY['Saches', 'Sachens', 'Sachener']),
('Lektion',          'die', 'Lektionen',        ARRAY['Lektione', 'Lektions', 'Lektionens']),
('Erde',             'die', NULL,               ARRAY['Erden', 'Erder', 'Erdes']),
('Schulter',         'die', 'Schultern',        ARRAY['Schultere', 'Schulters', 'Schulterens']),
('Brust',            'die', 'Brüste',           ARRAY['Bruste', 'Brüsten', 'Brusten']),
('Stirn',            'die', 'Stirnen',          ARRAY['Stirne', 'Stirns', 'Stirner']),
('Wange',            'die', 'Wangen',           ARRAY['Wanges', 'Wangens', 'Wangener']),
('Lippe',            'die', 'Lippen',           ARRAY['Lippes', 'Lippens', 'Lippener']),
('Wimper',           'die', 'Wimpern',          ARRAY['Wimpere', 'Wimpers', 'Wimperens']),
('Augenbraue',       'die', 'Augenbrauen',      ARRAY['Augenbraues', 'Augenbrauens', 'Augenbrauener']),
('Haut',             'die', NULL,               ARRAY['Hauten', 'Hauts', 'Haute']),
('Stimme',           'die', 'Stimmen',          ARRAY['Stimmes', 'Stimmens', 'Stimmener']),
('Träne',            'die', 'Tränen',           ARRAY['Tranen', 'Tränes', 'Träner']),
('Gesundheit',       'die', NULL,               ARRAY['Gesundheiten', 'Gesundheits', 'Gesundheite']),
('Krankheit',        'die', 'Krankheiten',      ARRAY['Krankheits', 'Krankheite', 'Krankheitern']),
('Medizin',          'die', 'Medizinen',        ARRAY['Medizine', 'Medizins', 'Mediziner']),
('Tablette',         'die', 'Tabletten',        ARRAY['Tabletes', 'Tabletter', 'Tabletens']),
('Spritze',          'die', 'Spritzen',         ARRAY['Spritzes', 'Spritzens', 'Spritzener']),
('Apotheke',         'die', 'Apotheken',        ARRAY['Apothekes', 'Apothekens', 'Apothekener']),
('Klinik',           'die', 'Kliniken',         ARRAY['Klinike', 'Kliniks', 'Kliniker']),
('Pflege',           'die', NULL,               ARRAY['Pflegen', 'Pflegs', 'Pfleges']),
('Diät',             'die', 'Diäten',           ARRAY['Diate', 'Diäts', 'Diäter']),
('Übung',            'die', 'Übungen',          ARRAY['Übunge', 'Übungs', 'Übunger']),
('Ruhe',             'die', NULL,               ARRAY['Ruhen', 'Ruhs', 'Ruher']),
('Müdigkeit',        'die', NULL,               ARRAY['Müdigkeiten', 'Müdigkeits', 'Müdigkeite']),
('Kraft',            'die', 'Kräfte',           ARRAY['Krafte', 'Kräften', 'Kraften']),
('Energie',          'die', NULL,               ARRAY['Energien', 'Energies', 'Energier']),
('Schuld',           'die', 'Schulden',         ARRAY['Schulde', 'Schulds', 'Schulder']),
('Pflicht',          'die', 'Pflichten',        ARRAY['Pflichts', 'Pflichter', 'Pflichte']),
('Freiheit',         'die', NULL,               ARRAY['Freiheiten', 'Freiheits', 'Freiheite']),
('Gerechtigkeit',    'die', NULL,               ARRAY['Gerechtigkeiten', 'Gerechtigkeits', 'Gerechtigkeite']),
('Wahrheit',         'die', NULL,               ARRAY['Wahrheiten', 'Wahrheits', 'Wahrheite']),
('Lüge',             'die', 'Lügen',            ARRAY['Luge', 'Lüges', 'Lüger']),
('Hoffnung',         'die', 'Hoffnungen',       ARRAY['Hoffnunge', 'Hoffnungs', 'Hoffnunger']),
('Angst',            'die', 'Ängste',           ARRAY['Angste', 'Ängsten', 'Angsten']),
('Freude',           'die', NULL,               ARRAY['Freuden', 'Freuds', 'Freudes']),
('Trauer',           'die', NULL,               ARRAY['Trauern', 'Trauers', 'Trauere']),
('Liebe',            'die', NULL,               ARRAY['Lieben', 'Liebs', 'Lieber']),
('Freundschaft',     'die', 'Freundschaften',   ARRAY['Freundschafte', 'Freundschafts', 'Freundschafter']),
('Ehe',              'die', 'Ehen',             ARRAY['Ehes', 'Ehens', 'Ehener']),
('Scheidung',        'die', 'Scheidungen',      ARRAY['Scheidunge', 'Scheidungs', 'Scheidunger']),
('Geburt',           'die', 'Geburten',         ARRAY['Geburte', 'Geburts', 'Geburter']),
('Kindheit',         'die', NULL,               ARRAY['Kindheiten', 'Kindheits', 'Kindheite']),
('Jugend',           'die', NULL,               ARRAY['Jugenden', 'Jugends', 'Jugender']),
('Zukunft',          'die', NULL,               ARRAY['Zukunfts', 'Zukunften', 'Zukunfte']),
('Vergangenheit',    'die', NULL,               ARRAY['Vergangenheiten', 'Vergangenheits', 'Vergangenheite']),
('Gegenwart',        'die', NULL,               ARRAY['Gegenwarten', 'Gegenwahrten', 'Gegenwarts']),
('Erfahrung',        'die', 'Erfahrungen',      ARRAY['Erfahrunge', 'Erfahrungs', 'Erfahrunger']),
('Meinung',          'die', 'Meinungen',        ARRAY['Meinunge', 'Meinungs', 'Meinunger']),
('Entscheidung',     'die', 'Entscheidungen',   ARRAY['Entscheidunge', 'Entscheidungs', 'Entscheidunger']),
('Lösung',           'die', 'Lösungen',         ARRAY['Lösunge', 'Lösungs', 'Lösunger']),
('Aufgabe',          'die', 'Aufgaben',         ARRAY['Aufgabes', 'Aufgabens', 'Aufgabener']),
('Prüfung',          'die', 'Prüfungen',        ARRAY['Prüfunge', 'Prüfungs', 'Prüfunger']),
('Note',             'die', 'Noten',            ARRAY['Notes', 'Notens', 'Noter']),
('Universität',      'die', 'Universitäten',    ARRAY['Universitate', 'Universitätens', 'Universitäters']),
('Bibliothek',       'die', 'Bibliotheken',     ARRAY['Bibliotheke', 'Bibliotheks', 'Bibliotheker']),
('Zeile',            'die', 'Zeilen',           ARRAY['Zeiles', 'Zeilens', 'Zeilener']),
('Seite',            'die', 'Seiten',           ARRAY['Seites', 'Seitens', 'Seitener']),
('Maus',             'die', 'Mäuse',            ARRAY['Mause', 'Mäusen', 'Mausen']),
('Kuh',              'die', 'Kühe',             ARRAY['Kuhe', 'Kühen', 'Kuhen']),
('Schlange',         'die', 'Schlangen',        ARRAY['Schlanges', 'Schlangener', 'Schlanger']),
('Spinne',           'die', 'Spinnen',          ARRAY['Spinnes', 'Spinnens', 'Spinnener']),
('Fliege',           'die', 'Fliegen',          ARRAY['Flieges', 'Fliegener', 'Flieger']),
('Biene',            'die', 'Bienen',           ARRAY['Bienes', 'Bienens', 'Bienener']),
('Ameise',           'die', 'Ameisen',          ARRAY['Ameises', 'Ameisens', 'Ameisener']),
('Mücke',            'die', 'Mücken',           ARRAY['Mucke', 'Mückes', 'Mückener']),
('Pflanze',          'die', 'Pflanzen',         ARRAY['Pflanzes', 'Pflanzens', 'Pflanzener']),
('Rose',             'die', 'Rosen',            ARRAY['Roses', 'Rosens', 'Rosener']),
('Tulpe',            'die', 'Tulpen',           ARRAY['Tulpes', 'Tulpens', 'Tulpener']),
('Wurzel',           'die', 'Wurzeln',          ARRAY['Wurzele', 'Wurzels', 'Wurzelens']),
('Frucht',           'die', 'Früchte',          ARRAY['Fruchte', 'Früchten', 'Fruchten']),
('Kartoffel',        'die', 'Kartoffeln',       ARRAY['Kartoffele', 'Kartoffels', 'Kartoffelens']),
('Tomate',           'die', 'Tomaten',          ARRAY['Tomates', 'Tomatens', 'Tomater']),
('Karotte',          'die', 'Karotten',         ARRAY['Karottes', 'Karottens', 'Karotter']),
('Zwiebel',          'die', 'Zwiebeln',         ARRAY['Zwiebelne', 'Zwiebelns', 'Zwiebelens']),
('Gurke',            'die', 'Gurken',           ARRAY['Gurkes', 'Gurkens', 'Gurkener']),
('Birne',            'die', 'Birnen',           ARRAY['Birnes', 'Birnens', 'Birnener']),
('Kirsche',          'die', 'Kirschen',         ARRAY['Kirsches', 'Kirschens', 'Kirschener']),
('Erdbeere',         'die', 'Erdbeeren',        ARRAY['Erdbeeres', 'Erdbeerens', 'Erdbeerer']),
('Banane',           'die', 'Bananen',          ARRAY['Bananes', 'Bananens', 'Bananener']),
('Orange',           'die', 'Orangen',          ARRAY['Oranges', 'Orangens', 'Orangener']),
('Zitrone',          'die', 'Zitronen',         ARRAY['Zitrones', 'Zitronens', 'Zitronener']),
('Traube',           'die', 'Trauben',          ARRAY['Traubes', 'Traubens', 'Traubener']),
('Butter',           'die', NULL,               ARRAY['Buttern', 'Butters', 'Buttere']),
('Marmelade',        'die', 'Marmeladen',       ARRAY['Marmelades', 'Marmeladens', 'Marmelader']),
('Soße',             'die', 'Soßen',            ARRAY['Soßes', 'Soßens', 'Soßener']),
('Nudel',            'die', 'Nudeln',           ARRAY['Nudele', 'Nudels', 'Nudelens']),
('Wurst',            'die', 'Würste',           ARRAY['Wurste', 'Würsten', 'Wursten']),
('Gabel',            'die', 'Gabeln',           ARRAY['Gabele', 'Gabels', 'Gabelens']),
('Tasse',            'die', 'Tassen',           ARRAY['Tasses', 'Tassens', 'Tassener']),
('Flasche',          'die', 'Flaschen',         ARRAY['Flasches', 'Flaschens', 'Flaschener']),
('Dose',             'die', 'Dosen',            ARRAY['Doses', 'Dosens', 'Dosener']),
('Pfanne',           'die', 'Pfannen',          ARRAY['Pfannes', 'Pfannens', 'Pfannener']),
('Schüssel',         'die', 'Schüsseln',        ARRAY['Schüssele', 'Schüssels', 'Schusseln']),
('Serviette',        'die', 'Servietten',       ARRAY['Servietes', 'Servietter', 'Serviettens']),
('Jacke',            'die', 'Jacken',           ARRAY['Jackes', 'Jackens', 'Jackener']),
('Hose',             'die', 'Hosen',            ARRAY['Hoses', 'Hosens', 'Hosener']),
('Bluse',            'die', 'Blusen',           ARRAY['Bluses', 'Blusens', 'Blusener']),
('Socke',            'die', 'Socken',           ARRAY['Sockes', 'Sockens', 'Sockener']),
('Mütze',            'die', 'Mützen',           ARRAY['Mützes', 'Mutzen', 'Mützener']),
('Brille',           'die', 'Brillen',          ARRAY['Brilles', 'Brillens', 'Brillener']),
('Kette',            'die', 'Ketten',           ARRAY['Kettes', 'Kettens', 'Kettener']),
('Weste',            'die', 'Westen',           ARRAY['Westes', 'Westens', 'Westener']),
('Schürze',          'die', 'Schürzen',         ARRAY['Schürzes', 'Schürzens', 'Schürzener']),

-- das (neuter)
('Kind',             'das', 'Kinder',           ARRAY['Kinde', 'Kindern', 'Kinds']),
('Haus',             'das', 'Häuser',           ARRAY['Hause', 'Häusern', 'Hausen']),
('Auto',             'das', 'Autos',            ARRAY['Autoen', 'Autone', 'Autoner']),
('Land',             'das', 'Länder',           ARRAY['Lande', 'Ländern', 'Landen']),
('Jahr',             'das', 'Jahre',            ARRAY['Jahren', 'Jahrs', 'Jahrer']),
('Buch',             'das', 'Bücher',           ARRAY['Buche', 'Büchern', 'Buchen']),
('Wasser',           'das', NULL,               ARRAY['Wassern', 'Wassers', 'Wassere']),
('Geld',             'das', NULL,               ARRAY['Gelder', 'Geldes', 'Gelden']),
('Wort',             'das', 'Wörter',           ARRAY['Worte', 'Wörtern', 'Words']),
('Bett',             'das', 'Betten',           ARRAY['Bette', 'Betts', 'Better']),
('Fenster',          'das', 'Fenster',          ARRAY['Fensters', 'Fenstere', 'Fenstern']),
('Zimmer',           'das', 'Zimmer',           ARRAY['Zimmers', 'Zimmere', 'Zimmern']),
('Essen',            'das', NULL,               ARRAY['Essens', 'Essener', 'Essenes']),
('Brot',             'das', 'Brote',            ARRAY['Broten', 'Brots', 'Broter']),
('Ei',               'das', 'Eier',             ARRAY['Eie', 'Eien', 'Eis']),
('Fleisch',          'das', NULL,               ARRAY['Fleischen', 'Fleischs', 'Fleische']),
('Restaurant',       'das', 'Restaurants',      ARRAY['Restauranten', 'Restaurantes', 'Restauranter']),
('Hotel',            'das', 'Hotels',           ARRAY['Hotelen', 'Hoteles', 'Hoteler']),
('Telefon',          'das', 'Telefone',         ARRAY['Telefonen', 'Telefons', 'Telefoner']),
('Spiel',            'das', 'Spiele',           ARRAY['Spielen', 'Spiels', 'Spieler']),
('Flugzeug',         'das', 'Flugzeuge',        ARRAY['Flugzeugen', 'Flugzeugs', 'Flugzeuger']),
('Fahrrad',          'das', 'Fahrräder',        ARRAY['Fahrrade', 'Fahrrädern', 'Fahrraden']),
('Wetter',           'das', NULL,               ARRAY['Wettern', 'Wetters', 'Wettere']),
('Leben',            'das', 'Leben',            ARRAY['Lebens', 'Lebene', 'Lebener']),
('Ende',             'das', 'Enden',            ARRAY['Endes', 'Endens', 'Endener']),
('Beispiel',         'das', 'Beispiele',        ARRAY['Beispielen', 'Beispiels', 'Beispieler']),
('Tier',             'das', 'Tiere',            ARRAY['Tieren', 'Tiers', 'Tierer']),
('Mädchen',          'das', 'Mädchen',          ARRAY['Mädchens', 'Mädchene', 'Mädchener']),
('Dorf',             'das', 'Dörfer',           ARRAY['Dorfe', 'Dörfern', 'Dorfen']),
('Meer',             'das', 'Meere',            ARRAY['Meeren', 'Meers', 'Meerer']),
('Auge',             'das', 'Augen',            ARRAY['Auges', 'Augens', 'Augener']),
('Ohr',              'das', 'Ohren',            ARRAY['Ohre', 'Ohrs', 'Ohrens']),
('Bein',             'das', 'Beine',            ARRAY['Beinen', 'Beins', 'Beiner']),
('Knie',             'das', 'Knie',             ARRAY['Knies', 'Knieen', 'Knier']),
('Gesicht',          'das', 'Gesichter',        ARRAY['Gesichte', 'Gesichtern', 'Gesichten']),
('Gehirn',           'das', 'Gehirne',          ARRAY['Gehirnen', 'Gehirns', 'Gehirner']),
('Herz',             'das', 'Herzen',           ARRAY['Herze', 'Herzs', 'Herzer']),
('Blut',             'das', NULL,               ARRAY['Bluten', 'Bluts', 'Blute']),
('Haar',             'das', 'Haare',            ARRAY['Haren', 'Haares', 'Haars']),
('Kinn',             'das', 'Kinne',            ARRAY['Kinnen', 'Kinns', 'Kinner']),
('Gebäude',          'das', 'Gebäude',          ARRAY['Gebäudes', 'Gebäudene', 'Gebäudern']),
('Büro',             'das', 'Büros',            ARRAY['Büroen', 'Büroe', 'Büroer']),
('Krankenhaus',      'das', 'Krankenhäuser',    ARRAY['Krankenhause', 'Krankenhäusern', 'Krankenhausen']),
('Rathaus',          'das', 'Rathäuser',        ARRAY['Rathause', 'Rathäusern', 'Rathauser']),
('Schloss',          'das', 'Schlösser',        ARRAY['Schlosse', 'Schlössern', 'Schlossen']),
('Museum',           'das', 'Museen',           ARRAY['Museume', 'Museums', 'Museumsens']),
('Theater',          'das', 'Theater',          ARRAY['Theaters', 'Theatere', 'Theatern']),
('Kino',             'das', 'Kinos',            ARRAY['Kinoen', 'Kinoe', 'Kinoer']),
('Stadion',          'das', 'Stadien',          ARRAY['Stadione', 'Stadions', 'Stadioner']),
('Schwimmbad',       'das', 'Schwimmbäder',     ARRAY['Schwimmbade', 'Schwimmbädern', 'Schwimmbadern']),
('Kaufhaus',         'das', 'Kaufhäuser',       ARRAY['Kaufhause', 'Kaufhäusern', 'Kaufhausen']),
('Geschäft',         'das', 'Geschäfte',        ARRAY['Geschafte', 'Geschäften', 'Geschaften']),
('Café',             'das', 'Cafés',            ARRAY['Cafeen', 'Cafee', 'Cafeer']),
('Konzert',          'das', 'Konzerte',         ARRAY['Konzerten', 'Konzerts', 'Konzerter']),
('Fest',             'das', 'Feste',            ARRAY['Festen', 'Fests', 'Fester']),
('Geschenk',         'das', 'Geschenke',        ARRAY['Geschenken', 'Geschenks', 'Geschenker']),
('Gedicht',          'das', 'Gedichte',         ARRAY['Gedichten', 'Gedichts', 'Gedichter']),
('Lied',             'das', 'Lieder',           ARRAY['Liede', 'Liedern', 'Liedens']),
('Instrument',       'das', 'Instrumente',      ARRAY['Instrumenten', 'Instruments', 'Instrumenter']),
('Klavier',          'das', 'Klaviere',         ARRAY['Klavieren', 'Klaviers', 'Klavierer']),
('Rezept',           'das', 'Rezepte',          ARRAY['Rezepten', 'Rezepts', 'Rezepter']),
('Getränk',          'das', 'Getränke',         ARRAY['Getranke', 'Getränken', 'Getranken']),
('Frühstück',        'das', 'Frühstücke',       ARRAY['Fruhstucke', 'Frühstücken', 'Fruhstucken']),
('Mittagessen',      'das', 'Mittagessen',      ARRAY['Mittagessens', 'Mittagessene', 'Mittagessener']),
('Abendessen',       'das', 'Abendessen',       ARRAY['Abendessens', 'Abendessene', 'Abendessener']),
('Gericht',          'das', 'Gerichte',         ARRAY['Gerichten', 'Gerichts', 'Gerichter']),
('Messer',           'das', 'Messer',           ARRAY['Messers', 'Messere', 'Messern']),
('Glas',             'das', 'Gläser',           ARRAY['Glase', 'Gläsern', 'Glasen']),
('Hemd',             'das', 'Hemden',           ARRAY['Hemde', 'Hemds', 'Hemder']),
('Kleid',            'das', 'Kleider',          ARRAY['Kleide', 'Kleidern', 'Kleids']),
('T-Shirt',          'das', 'T-Shirts',         ARRAY['T-Shirten', 'T-Shirtens', 'T-Shirtes']),
('Handtuch',         'das', 'Handtücher',       ARRAY['Handtuche', 'Handtüchern', 'Handtuchen']),
('Kissen',           'das', 'Kissen',           ARRAY['Kissens', 'Kissene', 'Kissern']),
('Laken',            'das', 'Laken',            ARRAY['Lakens', 'Lakene', 'Lakern']),
('Motorrad',         'das', 'Motorräder',       ARRAY['Motorrade', 'Motorrädern', 'Motorraden']),
('Schiff',           'das', 'Schiffe',          ARRAY['Schiffen', 'Schiffs', 'Schiffer']),
('Boot',             'das', 'Boote',            ARRAY['Booten', 'Boots', 'Booter']),
('Taxi',             'das', 'Taxis',            ARRAY['Taxien', 'Taxie', 'Taxies']),
('Ticket',           'das', 'Tickets',          ARRAY['Ticketen', 'Ticketes', 'Ticketer']),
('Gepäck',           'das', NULL,               ARRAY['Gepäcke', 'Gepäcks', 'Gepäcken']),
('Ziel',             'das', 'Ziele',            ARRAY['Zielen', 'Ziels', 'Zieler']),
('Ergebnis',         'das', 'Ergebnisse',       ARRAY['Ergebnisen', 'Ergebnisr', 'Ergebnissen']),
('Thema',            'das', 'Themen',           ARRAY['Theme', 'Themas', 'Themer']),
('Problem',          'das', 'Probleme',         ARRAY['Problemen', 'Problems', 'Problemer']),
('Projekt',          'das', 'Projekte',         ARRAY['Projekten', 'Projekts', 'Projekter']),
('System',           'das', 'Systeme',          ARRAY['Systemen', 'Systems', 'Systemer']),
('Programm',         'das', 'Programme',        ARRAY['Programmen', 'Programms', 'Programmer']),
('Netz',             'das', 'Netze',            ARRAY['Netzen', 'Netzs', 'Netzer']),
('Internet',         'das', NULL,               ARRAY['Internets', 'Interneten', 'Internete']),
('Handy',            'das', 'Handys',           ARRAY['Handyen', 'Handyes', 'Handyer']),
('Foto',             'das', 'Fotos',            ARRAY['Fotoen', 'Fotoe', 'Foton']),
('Video',            'das', 'Videos',           ARRAY['Videon', 'Vidoes', 'Vidoer']),
('Hobby',            'das', 'Hobbys',           ARRAY['Hobbyen', 'Hobbyes', 'Hobbyer']),
('Talent',           'das', 'Talente',          ARRAY['Talenten', 'Talents', 'Talenter']),
('Glück',            'das', NULL,               ARRAY['Glücke', 'Glücks', 'Glücken']),
('Pech',             'das', NULL,               ARRAY['Peche', 'Pechs', 'Pechen']),
('Wunder',           'das', 'Wunder',           ARRAY['Wunders', 'Wundere', 'Wundern']),
('Geheimnis',        'das', 'Geheimnisse',      ARRAY['Geheimnis', 'Geheimnisen', 'Geheimnissen']),
('Abenteuer',        'das', 'Abenteuer',        ARRAY['Abenteuers', 'Abenteuerens', 'Abenteuerern']),
('Risiko',           'das', 'Risiken',          ARRAY['Risikos', 'Risikoen', 'Risikoner']),
('Angebot',          'das', 'Angebote',         ARRAY['Angeboten', 'Angebots', 'Angeboter']);

INSERT INTO vocabulary.public_noun_de_translation (noun_id, lang, sort_order, translation)
SELECT n.id, 'it', 1, t.translation
FROM (VALUES
  ('Mann', 'uomo'), ('Vater', 'padre'), ('Bruder', 'fratello'), ('Sohn', 'figlio'),
  ('Freund', 'amico'), ('Tag', 'giorno'), ('Morgen', 'mattina'), ('Abend', 'sera'),
  ('Monat', 'mese'), ('Sommer', 'estate'), ('Winter', 'inverno'), ('Herbst', 'autunno'),
  ('Frühling', 'primavera'), ('Beruf', 'professione'), ('Tisch', 'tavolo'), ('Stuhl', 'sedia'),
  ('Weg', 'via'), ('Baum', 'albero'), ('Berg', 'montagna'), ('Hund', 'cane'),
  ('Vogel', 'uccello'), ('Fisch', 'pesce'), ('Apfel', 'mela'), ('Käse', 'formaggio'),
  ('Kaffee', 'caffè'), ('Tee', 'tè'), ('Arzt', 'medico'), ('Lehrer', 'insegnante'),
  ('Student', 'studente'), ('Computer', 'computer'), ('Film', 'film'), ('Bus', 'autobus'),
  ('Zug', 'treno'), ('Garten', 'giardino'), ('Park', 'parco'), ('Himmel', 'cielo'),
  ('Name', 'nome'), ('Fluss', 'fiume'), ('Brief', 'lettera'), ('Markt', 'mercato'),
  ('Schlüssel', 'chiave'), ('Regen', 'pioggia'), ('Schnee', 'neve'), ('Wind', 'vento'),
  ('Mond', 'luna'), ('Stern', 'stella'), ('König', 're'), ('Schuh', 'scarpa'),
  ('Fehler', 'errore'), ('Preis', 'prezzo'), ('Körper', 'corpo'), ('Kopf', 'testa'),
  ('Arm', 'braccio'), ('Finger', 'dito'), ('Fuß', 'piede'), ('Rücken', 'schiena'),
  ('Bauch', 'pancia'), ('Mund', 'bocca'), ('Hals', 'collo'), ('Zahn', 'dente'),
  ('Bart', 'barba'), ('Haare', 'capelli'), ('Laden', 'negozio'), ('Supermarkt', 'supermercato'),
  ('Bäcker', 'panettiere'), ('Metzger', 'macellaio'), ('Kellner', 'cameriere'), ('Fahrer', 'autista'),
  ('Ingenieur', 'ingegnere'), ('Anwalt', 'avvocato'), ('Politiker', 'politico'), ('Soldat', 'soldato'),
  ('Pilot', 'pilota'), ('Koch', 'cuoco'), ('Bauer', 'contadino'), ('Künstler', 'artista'),
  ('Musiker', 'musicista'), ('Sportler', 'sportivo'), ('Schüler', 'alunno'), ('Nachbar', 'vicino'),
  ('Gast', 'ospite'), ('Freier', 'cliente'), ('Boden', 'pavimento'), ('Raum', 'spazio'),
  ('Platz', 'posto'), ('Eingang', 'entrata'), ('Ausgang', 'uscita'), ('Aufzug', 'ascensore'),
  ('Keller', 'cantina'), ('Dachboden', 'soffitta'), ('Schrank', 'armadio'), ('Spiegel', 'specchio'),
  ('Teppich', 'tappeto'), ('Vorhang', 'tenda'), ('Herd', 'fornello'), ('Kühlschrank', 'frigorifero'),
  ('Fernseher', 'televisore'), ('Drucker', 'stampante'), ('Stecker', 'spina'), ('Schalter', 'interruttore'),
  ('Topf', 'pentola'), ('Löffel', 'cucchiaio'), ('Teller', 'piatto'), ('Becher', 'bicchiere'),
  ('Stift', 'penna'), ('Bleistift', 'matita'), ('Kalender', 'calendario'), ('Ausweis', 'documento'),
  ('Reisepass', 'passaporto'), ('Führerschein', 'patente'), ('Vertrag', 'contratto'), ('Antrag', 'richiesta'),
  ('Bericht', 'rapporto'), ('Artikel', 'articolo'), ('Roman', 'romanzo'), ('Autor', 'autore'),
  ('Verlag', 'casa editrice'), ('Lärm', 'rumore'), ('Geruch', 'odore'), ('Geschmack', 'gusto'),
  ('Traum', 'sogno'), ('Gedanke', 'pensiero'), ('Witz', 'barzelletta'), ('Krach', 'fracasso'),
  ('Schaden', 'danno'), ('Unfall', 'incidente'), ('Brand', 'incendio'), ('Sturm', 'tempesta'),
  ('Nebel', 'nebbia'), ('Frost', 'gelo'), ('Schatten', 'ombra'), ('Sonnenuntergang', 'tramonto'),
  ('Sonnenaufgang', 'alba'), ('Wald', 'bosco'), ('See', 'lago'), ('Strand', 'spiaggia'),
  ('Sand', 'sabbia'), ('Stein', 'pietra'), ('Fels', 'roccia'), ('Hügel', 'collina'),
  ('Vulkan', 'vulcano'), ('Flug', 'volo'), ('Hafen', 'porto'), ('Bahnhof', 'stazione'),
  ('Flughafen', 'aeroporto'), ('Stau', 'ingorgo'), ('Kilometer', 'chilometro'), ('Meter', 'metro'),
  ('Liter', 'litro'), ('Grad', 'grado'), ('Euro', 'euro'), ('Cent', 'centesimo'),
  ('Gewinn', 'guadagno'), ('Verlust', 'perdita'), ('Kredit', 'credito'), ('Rabatt', 'sconto'),
  ('Scheck', 'assegno'), ('Betrag', 'importo'), ('Unterschied', 'differenza'), ('Vorteil', 'vantaggio'),
  ('Nachteil', 'svantaggio'), ('Erfolg', 'successo'), ('Misserfolg', 'insuccesso'), ('Anfang', 'inizio'),
  ('Schluss', 'conclusione'), ('Grund', 'motivo'), ('Zweck', 'scopo'), ('Schritt', 'passo'),
  ('Fortschritt', 'progresso'), ('Versuch', 'tentativo'), ('Beweis', 'prova'), ('Begriff', 'concetto'),
  ('Satz', 'frase'),
  ('Frau', 'donna'), ('Mutter', 'madre'), ('Schwester', 'sorella'), ('Tochter', 'figlia'),
  ('Zeit', 'tempo'), ('Nacht', 'notte'), ('Woche', 'settimana'), ('Schule', 'scuola'),
  ('Arbeit', 'lavoro'), ('Stadt', 'città'), ('Straße', 'strada'), ('Familie', 'famiglia'),
  ('Küche', 'cucina'), ('Sprache', 'lingua'), ('Musik', 'musica'), ('Katze', 'gatto'),
  ('Blume', 'fiore'), ('Sonne', 'sole'), ('Brücke', 'ponte'), ('Uhr', 'orologio'),
  ('Zeitung', 'giornale'), ('Tasche', 'borsa'), ('Farbe', 'colore'), ('Antwort', 'risposta'),
  ('Frage', 'domanda'), ('Geschichte', 'storia'), ('Kirche', 'chiesa'), ('Wohnung', 'appartamento'),
  ('Milch', 'latte'), ('Suppe', 'zuppa'), ('Hand', 'mano'), ('Nase', 'naso'),
  ('Nummer', 'numero'), ('Adresse', 'indirizzo'), ('Tür', 'porta'), ('Wand', 'parete'),
  ('Treppe', 'scala'), ('Insel', 'isola'), ('Luft', 'aria'), ('Natur', 'natura'),
  ('Reise', 'viaggio'), ('Stunde', 'ora'), ('Minute', 'minuto'), ('Küste', 'costa'),
  ('Welt', 'mondo'), ('Freundin', 'amica'), ('Lehrerin', 'insegnante'), ('Sache', 'cosa'),
  ('Lektion', 'lezione'), ('Erde', 'terra'), ('Schulter', 'spalla'), ('Brust', 'petto'),
  ('Stirn', 'fronte'), ('Wange', 'guancia'), ('Lippe', 'labbro'), ('Wimper', 'ciglio'),
  ('Augenbraue', 'sopracciglio'), ('Haut', 'pelle'), ('Stimme', 'voce'), ('Träne', 'lacrima'),
  ('Gesundheit', 'salute'), ('Krankheit', 'malattia'), ('Medizin', 'medicina'), ('Tablette', 'pastiglia'),
  ('Spritze', 'iniezione'), ('Apotheke', 'farmacia'), ('Klinik', 'clinica'), ('Pflege', 'cura'),
  ('Diät', 'dieta'), ('Übung', 'esercizio'), ('Ruhe', 'riposo'), ('Müdigkeit', 'stanchezza'),
  ('Kraft', 'forza'), ('Energie', 'energia'), ('Schuld', 'colpa'), ('Pflicht', 'dovere'),
  ('Freiheit', 'libertà'), ('Gerechtigkeit', 'giustizia'), ('Wahrheit', 'verità'), ('Lüge', 'bugia'),
  ('Hoffnung', 'speranza'), ('Angst', 'paura'), ('Freude', 'gioia'), ('Trauer', 'tristezza'),
  ('Liebe', 'amore'), ('Freundschaft', 'amicizia'), ('Ehe', 'matrimonio'), ('Scheidung', 'divorzio'),
  ('Geburt', 'nascita'), ('Kindheit', 'infanzia'), ('Jugend', 'gioventù'), ('Zukunft', 'futuro'),
  ('Vergangenheit', 'passato'), ('Gegenwart', 'presente'), ('Erfahrung', 'esperienza'), ('Meinung', 'opinione'),
  ('Entscheidung', 'decisione'), ('Lösung', 'soluzione'), ('Aufgabe', 'compito'), ('Prüfung', 'esame'),
  ('Note', 'voto'), ('Universität', 'università'), ('Bibliothek', 'biblioteca'), ('Zeile', 'riga'),
  ('Seite', 'pagina'), ('Maus', 'topo'), ('Kuh', 'mucca'), ('Schlange', 'serpente'),
  ('Spinne', 'ragno'), ('Fliege', 'mosca'), ('Biene', 'ape'), ('Ameise', 'formica'),
  ('Mücke', 'zanzara'), ('Pflanze', 'pianta'), ('Rose', 'rosa'), ('Tulpe', 'tulipano'),
  ('Wurzel', 'radice'), ('Frucht', 'frutto'), ('Kartoffel', 'patata'), ('Tomate', 'pomodoro'),
  ('Karotte', 'carota'), ('Zwiebel', 'cipolla'), ('Gurke', 'cetriolo'), ('Birne', 'pera'),
  ('Kirsche', 'ciliegia'), ('Erdbeere', 'fragola'), ('Banane', 'banana'), ('Orange', 'arancia'),
  ('Zitrone', 'limone'), ('Traube', 'uva'), ('Butter', 'burro'), ('Marmelade', 'marmellata'),
  ('Soße', 'salsa'), ('Nudel', 'pasta'), ('Wurst', 'salame'), ('Gabel', 'forchetta'),
  ('Tasse', 'tazza'), ('Flasche', 'bottiglia'), ('Dose', 'lattina'), ('Pfanne', 'padella'),
  ('Schüssel', 'ciotola'), ('Serviette', 'tovagliolo'), ('Jacke', 'giacca'), ('Hose', 'pantaloni'),
  ('Bluse', 'camicetta'), ('Socke', 'calzino'), ('Mütze', 'berretto'), ('Brille', 'occhiali'),
  ('Kette', 'collana'), ('Weste', 'gilet'), ('Schürze', 'grembiule'),
  ('Kind', 'bambino'), ('Haus', 'casa'), ('Auto', 'automobile'), ('Land', 'paese'),
  ('Jahr', 'anno'), ('Buch', 'libro'), ('Wasser', 'acqua'), ('Geld', 'denaro'),
  ('Wort', 'parola'), ('Bett', 'letto'), ('Fenster', 'finestra'), ('Zimmer', 'stanza'),
  ('Essen', 'cibo'), ('Brot', 'pane'), ('Ei', 'uovo'), ('Fleisch', 'carne'),
  ('Restaurant', 'ristorante'), ('Hotel', 'hotel'), ('Telefon', 'telefono'), ('Spiel', 'gioco'),
  ('Flugzeug', 'aereo'), ('Fahrrad', 'bicicletta'), ('Wetter', 'tempo'), ('Leben', 'vita'),
  ('Ende', 'fine'), ('Beispiel', 'esempio'), ('Tier', 'animale'), ('Mädchen', 'ragazza'),
  ('Dorf', 'villaggio'), ('Meer', 'mare'), ('Auge', 'occhio'), ('Ohr', 'orecchio'),
  ('Bein', 'gamba'), ('Knie', 'ginocchio'), ('Gesicht', 'viso'), ('Gehirn', 'cervello'),
  ('Herz', 'cuore'), ('Blut', 'sangue'), ('Haar', 'capello'), ('Kinn', 'mento'),
  ('Gebäude', 'edificio'), ('Büro', 'ufficio'), ('Krankenhaus', 'ospedale'), ('Rathaus', 'municipio'),
  ('Schloss', 'castello'), ('Museum', 'museo'), ('Theater', 'teatro'), ('Kino', 'cinema'),
  ('Stadion', 'stadio'), ('Schwimmbad', 'piscina'), ('Kaufhaus', 'grande magazzino'), ('Geschäft', 'negozio'),
  ('Café', 'caffè'), ('Konzert', 'concerto'), ('Fest', 'festa'), ('Geschenk', 'regalo'),
  ('Gedicht', 'poesia'), ('Lied', 'canzone'), ('Instrument', 'strumento'), ('Klavier', 'pianoforte'),
  ('Rezept', 'ricetta'), ('Getränk', 'bevanda'), ('Frühstück', 'colazione'), ('Mittagessen', 'pranzo'),
  ('Abendessen', 'cena'), ('Gericht', 'piatto'), ('Messer', 'coltello'), ('Glas', 'bicchiere'),
  ('Hemd', 'camicia'), ('Kleid', 'vestito'), ('T-Shirt', 'maglietta'), ('Handtuch', 'asciugamano'),
  ('Kissen', 'cuscino'), ('Laken', 'lenzuolo'), ('Motorrad', 'moto'), ('Schiff', 'nave'),
  ('Boot', 'barca'), ('Taxi', 'taxi'), ('Ticket', 'biglietto'), ('Gepäck', 'bagaglio'),
  ('Ziel', 'meta'), ('Ergebnis', 'risultato'), ('Thema', 'tema'), ('Problem', 'problema'),
  ('Projekt', 'progetto'), ('System', 'sistema'), ('Programm', 'programma'), ('Netz', 'rete'),
  ('Internet', 'internet'), ('Handy', 'cellulare'), ('Foto', 'foto'), ('Video', 'video'),
  ('Hobby', 'hobby'), ('Talent', 'talento'), ('Glück', 'fortuna'), ('Pech', 'sfortuna'),
  ('Wunder', 'miracolo'), ('Geheimnis', 'segreto'), ('Abenteuer', 'avventura'), ('Risiko', 'rischio'),
  ('Angebot', 'offerta')
) AS t(word_de, translation)
JOIN vocabulary.public_noun_de n ON n.word_de = t.word_de;
